{
 "title": "GuestBook",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "AppCPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU_usage_Total(secs)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"deployment\", container_name =~ \"master|slave|php-redis\"}[5m])) by (container_name)"
    }
   ]
  },
  {
   "title": "ApplicationMemoryUsage",
   "type": "graph",
   "description": "Application Memory Monitoring",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Memory(KBytes)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=\"deployment\", container_name =~ \"master|slave|php-redis\"}[3m])/1024) by (container)"
    }
   ]
  },
  {
   "title": "AppCpu comsumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "TotalCPU(secs)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"deployment\"}[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "graph",
   "description": "Per K8S Node memory utilization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{}[2m])/1024) by (instance)"
    }
   ]
  }
 ]
}